// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "sl_si91x_rgb_led_config.h"
#include "sl_si91x_rgb_led_instances.h"
#include "sl_si91x_rgb_led.h"

#define ON   1
#define OFF  0

static volatile bool led0_status = OFF;

void btn0_pressed_event_cb(lv_event_t *e)
{
  (void)e;
  if (led0_status == ON) {
    sl_si91x_simple_rgb_led_off(&led_led0);
    led0_status = OFF;
  } else {
    sl_si91x_simple_rgb_led_on(&led_led0);
    led0_status = ON;
  }
}
